services:
  ping1:
    image: alpine:latest
    container_name: ping1
    command: sh -c "ping ping1 2>&1 1>/dev/null"
    restart: unless-stopped

  ping2:
    image: alpine:latest
    container_name: ping2
    command: sh -c "ping ping2 2>&1 1>/dev/null"
    restart: unless-stopped
  
  ping3:
    image: alpine:latest
    container_name: ping3
    command: sh -c "echo 'pinging container1' && ping ping1 && echo 'pinging container2' && ping ping2"
    restart: unless-stopped
